version: '3.7'

services:
  mongodb:
    build: ./mongo
    container_name: mongo
    hostname: mongo
    volumes:
        - ./mongo/mongod.conf:/etc/mongod.conf
        - ./data/mongodata/data/db/:/data/db/
    env_file:
        - .env
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
        - "27017:27017"
    
  go:
    container_name: 'go'
    build: ./go
    restart: always
    volumes:
        - ./go/start.sh:/start.sh
        - ../services:/go/src/services
    command: '/bin/sh /start.sh'
    network_mode: 'host'
    ports: 
        - "8888:8888"

  db:
    container_name: 'postgres'
    build: ./postgres
    network_mode: "host"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
      - ../../:/src/
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
